#!/usr/bin/env python3
"""
Build the weekly seminar PPTX from its Markdown file.

Reads a deck Markdown file, asks deck_parser to turn it
into sections, asks deck_layout to place everything on
slides, then writes a 16:9 PowerPoint file. Nothing is
positioned by hand: the slide count, the font sizes, and
every rectangle come out of deck_layout.

Three kinds of page are produced:

  content     a title plus one to three news blocks, each
              with a headline, bullets, and a picture
  toc         a contents page in three columns, generated
              from every headline in the file
  benchmarks  the LM Arena top 25 in two plain columns,
              read from the JSON that leaderboard.py writes

Inline markup inside a bullet: **bold** and ==highlight==.
A bullet holding only a URL becomes a small blue link.

Pictures are fitted into their box with the aspect ratio
preserved. An image file that is missing is reported and
its block falls back to full slide width.

Needs no network, so it is safe to run minutes before the
seminar: edit the Markdown, run this, open the PPTX. With
no argument it picks the newest deck Markdown in the
current directory, so the usual case is one short command.

Output is always "<deck>-generated.pptx". Hand-made decks
are protected: every file this script writes is marked in
its core properties, and it refuses to overwrite a PPTX
that lacks the mark unless --force is given.

Usage:
    python3 s3_make_pptx.py
    python3 s3_make_pptx.py 2026-09-18-AI-News.md
    python3 s3_make_pptx.py deck.md out.pptx --force

Run s1_fetch_images.py and s2_clean_images.py first, and
leaderboard.py if the benchmark page should be refreshed.

Created: 2026-09-12
Last updated: 2026-09-12
"""

import glob
import json
import os
import sys
from datetime import datetime

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches

import deck_layout as L
from bench_page import render_benchmarks_page
from pptx_text import (
    BOX_PAD, COLOR_BORDER, BORDER_WIDTH, COLOR_LINK,
    COLOR_TEXT, FONT, add_link_para, add_rich_para,
    add_headline_para, add_textbox, center, first_or_new,
    set_bullet, style_run,
)
from deck_parser import (
    DeckError, KIND_BENCHMARKS, KIND_TOC, all_headlines,
    deleted_count, deleted_sidecar_path, is_link,
    live_blocks, live_sections, parse_deck_file,
    read_deleted_topics, recreated_topics, split_markup,
)

LEADERBOARD_JSON = "resources_raw/leaderboard.json"
BLANK_LAYOUT = 6

DECK_GLOB = "*-AI-News.md"
GENERATED_SUFFIX = "-generated.pptx"

# Written into the core properties of every PPTX this
# script produces. It is the only way to tell one of our
# files from a hand-made deck, which is what stops an
# accidental overwrite of five years of archive.
GENERATED_MARK = "generated by s3_make_pptx.py"

# Pictures are drawn at their natural size for this
# resolution and never stretched past it. s2_clean_images.py
# scales to the same number, so a full-size picture exactly
# fills its box and a small one stays small and sharp.
IMAGE_PPI = 150

TOC_COLUMNS = 3
TOC_SIZE = 14

# The week's epigraph, drawn red, bold and italic at the top
# right of the contents page, exactly as in the hand-made
# decks. No fill and no border: it is a remark, not a box.
EPIGRAPH_SIZE = 18
EPIGRAPH_X = 5.90
EPIGRAPH_Y = 0.06
EPIGRAPH_GAP = 0.10
EPIGRAPH_MAX_LINES = 2
COLOR_EPIGRAPH = RGBColor(0xFF, 0x00, 0x00)

# --------------------------------------------------------------
def log_message(message):
    """Print timestamped log message."""
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{stamp}] {message}")


# --------------------------------------------------------------
def new_presentation():
    """Create an empty 16:9 presentation, 10 x 5.625 in."""
    prs = Presentation()
    prs.slide_width = Inches(L.SLIDE_W)
    prs.slide_height = Inches(L.SLIDE_H)
    return prs


# --------------------------------------------------------------
def add_slide(prs):
    """Append one blank slide."""
    return prs.slides.add_slide(
        prs.slide_layouts[BLANK_LAYOUT]
    )




# --------------------------------------------------------------
def render_block_text(slide, item, boxed=True):
    """Draw the headline and bullets of one news block."""
    frame = add_textbox(
        slide, item.text, boxed=boxed, fit=True
    )
    used = 0
    if item.block.headline:
        add_headline_para(
            frame, item.block.headline,
            L.headline_size(item.block, item.size), used
        )
        used = 1
    for text in item.block.bullets:
        if is_link(text):
            add_link_para(
                frame, text, used,
                L.link_size(item.size)
            )
        else:
            para = add_rich_para(
                frame, split_markup(text), item.size, used
            )
            if not L.is_promo(item.block):
                set_bullet(para, item.size)
        used += 1


# --------------------------------------------------------------
def image_size(path):
    """Return (width, height) in pixels, or None."""
    try:
        from PIL import Image
        with Image.open(path) as img:
            return img.size
    except Exception as exc:
        log_message(f"  cannot read {path}: {exc}")
        return None


# --------------------------------------------------------------
def fit_rect(path, rect):
    """Fit an image inside a Rect, keeping aspect ratio."""
    size = image_size(path)
    if not size:
        return None
    src_w, src_h = size
    scale = min(
        rect.w / src_w, rect.h / src_h, 1.0 / IMAGE_PPI
    )
    width = src_w * scale
    height = src_h * scale
    left = rect.x + (rect.w - width) / 2
    top = rect.y + (rect.h - height) / 2
    return L.Rect(left, top, width, height)


# --------------------------------------------------------------
def render_block_image(slide, item):
    """Place one block's picture, centered in its box."""
    path = item.block.image
    if not path or not item.image:
        return
    box = fit_rect(path, item.image)
    if not box:
        return
    picture = slide.shapes.add_picture(
        path, Inches(box.x), Inches(box.y),
        Inches(box.w), Inches(box.h)
    )
    picture.line.color.rgb = COLOR_BORDER
    picture.line.width = BORDER_WIDTH


# --------------------------------------------------------------
def render_title(slide, text, width=None):
    """Draw the slide title, when the page has one."""
    if not text:
        return
    rect = L.Rect(
        L.MARGIN, L.TITLE_Y,
        L.title_width(text, width), L.TITLE_H
    )
    frame = add_textbox(slide, rect, wrap=False)
    run = frame.paragraphs[0].add_run()
    run.text = text
    style_run(run, L.TITLE_SIZE, bold=True)


# --------------------------------------------------------------
def render_closing_title(slide, text):
    """Draw the big centred title of the sign-off page."""
    if not text:
        return
    frame = add_textbox(slide, L.closing_title_rect())
    para = frame.paragraphs[0]
    center(para)
    run = para.add_run()
    run.text = text
    style_run(run, L.CLOSING_TITLE_SIZE, bold=True)


# --------------------------------------------------------------
def render_content_page(slide, page):
    """Draw a title plus every placed news block."""
    if page.closing:
        render_closing_title(slide, page.title)
    else:
        render_title(slide, page.title)
    for item in page.items:
        render_block_text(
            slide, item, boxed=not page.plain
        )
        render_block_image(slide, item)


# --------------------------------------------------------------
def toc_columns(names):
    """Split headlines into equal top-to-bottom columns."""
    if not names:
        return []
    per = -(-len(names) // TOC_COLUMNS)
    return [names[i:i + per] for i in range(0, len(names), per)]


# --------------------------------------------------------------
def epigraph_width():
    """Width of the epigraph box at the top right."""
    return L.SLIDE_W - L.MARGIN - EPIGRAPH_X


# --------------------------------------------------------------
def epigraph_height(text):
    """Height the epigraph needs at its own size."""
    lines = L.wrapped_lines(
        text, epigraph_width(), EPIGRAPH_SIZE, bold=True
    )
    tall = lines * L.points_to_inches(
        EPIGRAPH_SIZE * L.LINE_RATIO
    )
    return tall + BOX_PAD


# --------------------------------------------------------------
def check_epigraph(text):
    """Warn when the epigraph is too long to sit neatly."""
    lines = L.wrapped_lines(
        text, epigraph_width(), EPIGRAPH_SIZE, bold=True
    )
    if lines > EPIGRAPH_MAX_LINES:
        log_message(
            f"WARNING: the epigraph wraps to {lines} lines "
            f"and crowds the contents page"
        )
        log_message(
            "  Shorten it to about 70 characters."
        )


# --------------------------------------------------------------
def render_epigraph(slide, text):
    """Draw the week's epigraph, returning its bottom."""
    if not text:
        return L.BAND_TOP
    check_epigraph(text)
    rect = L.Rect(
        EPIGRAPH_X, EPIGRAPH_Y,
        epigraph_width(), epigraph_height(text)
    )
    frame = add_textbox(slide, rect, fit=True)
    run = frame.paragraphs[0].add_run()
    run.text = text
    style_run(
        run, EPIGRAPH_SIZE, bold=True, color=COLOR_EPIGRAPH
    )
    run.font.italic = True
    return max(L.BAND_TOP, rect.y + rect.h + EPIGRAPH_GAP)


# --------------------------------------------------------------
def toc_column_height(column, width):
    """Height a contents column needs for its lines."""
    lines = sum(
        L.wrapped_lines(name, width, TOC_SIZE)
        for name in column
    )
    tall = lines * L.points_to_inches(
        TOC_SIZE * L.LINE_RATIO
    )
    return min(L.BAND_H, tall + BOX_PAD)


# --------------------------------------------------------------
def render_toc_page(slide, page, names, epigraph=""):
    """Draw the generated table of contents."""
    if epigraph:
        render_title(
            slide, page.title,
            EPIGRAPH_X - L.MARGIN - EPIGRAPH_GAP
        )
    else:
        render_title(slide, page.title)
    top = render_epigraph(slide, epigraph)

    columns = toc_columns(names)
    if not columns:
        return
    gap = 0.14
    width = (L.CONTENT_W - gap * (len(columns) - 1))
    width = width / len(columns)
    for index, column in enumerate(columns):
        left = L.MARGIN + index * (width + gap)
        rect = L.Rect(
            left, top, width,
            min(L.BAND_BOT - top,
                toc_column_height(column, width))
        )
        frame = add_textbox(slide, rect, boxed=True, fit=True)
        for used, name in enumerate(column):
            para = first_or_new(frame, used)
            run = para.add_run()
            run.text = name
            style_run(run, TOC_SIZE)


# --------------------------------------------------------------
def load_leaderboard(base):
    """Read the benchmark JSON leaderboard.py writes."""
    path = os.path.join(base, LEADERBOARD_JSON)
    if not os.path.isfile(path):
        log_message(f"WARNING: {LEADERBOARD_JSON} not found. "
                    f"Run: python3 leaderboard.py")
        return None
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)




# --------------------------------------------------------------
def render_page(prs, page, names, bench, epigraph=""):
    """Draw one page of any kind onto a new slide."""
    slide = add_slide(prs)
    if page.kind == KIND_TOC:
        render_toc_page(slide, page, names, epigraph)
    elif page.kind == KIND_BENCHMARKS:
        render_title(slide, page.title or "Benchmarks")
        render_benchmarks_page(slide, bench)
    else:
        render_content_page(slide, page)


# --------------------------------------------------------------
def resolve_images(deck, base):
    """Make image paths relative to the deck file itself.

    This is what lets the script run from any directory,
    instead of only from the one holding "images".
    """
    missing = 0
    for section in live_sections(deck):
        for block in live_blocks(section):
            if not block.image:
                continue
            named = block.image
            path = os.path.join(base, named)
            if os.path.isfile(path):
                block.image = path
                continue
            log_message(
                f"WARNING: missing image {named} "
                f"for '{block.headline}'"
            )
            block.image = None
            missing += 1
    return missing


# --------------------------------------------------------------
def report_recreated(deck, source):
    """Warn when a thrown-out topic is back in the deck."""
    deleted = read_deleted_topics(source)
    if not deleted:
        return 0, 0

    back = recreated_topics(deck, deleted)
    sidecar = os.path.basename(deleted_sidecar_path(source))
    for headline, topic in back:
        log_message(f"WARNING: '{headline}'")
        log_message(f"  matches '{topic}' in {sidecar}")
    if back:
        log_message(
            "A topic the author threw out is on a slide "
            "again. Remove it from the deck, or take it out "
            "of the deleted file if you want it back."
        )
    return len(deleted), len(back)


# --------------------------------------------------------------
def report_overflow(pages):
    """Warn about pages whose text may still be clipped."""
    count = 0
    for index, page in enumerate(pages, start=1):
        if page.overflow <= 0.01:
            continue
        count += 1
        log_message(
            f"WARNING: slide {index} '{page.title}' "
            f"overflows by {page.overflow:.2f} in"
        )
    return count


# --------------------------------------------------------------
def newest_deck():
    """Find the newest deck Markdown in this directory."""
    names = sorted(glob.glob(DECK_GLOB))
    return names[-1] if names else None


# --------------------------------------------------------------
def default_target(source):
    """Build the -generated.pptx name for a deck file."""
    return os.path.splitext(source)[0] + GENERATED_SUFFIX


# --------------------------------------------------------------
def resolve_paths(argv):
    """Work out the input and output file paths."""
    named = [a for a in argv[1:] if not a.startswith("-")]

    source = named[0] if named else newest_deck()
    if not source:
        log_message(
            f"ERROR: no {DECK_GLOB} file here. "
            f"Usage: python3 s3_make_pptx.py deck.md"
        )
        sys.exit(1)
    if not os.path.isfile(source):
        log_message(f"ERROR: {source} not found")
        sys.exit(1)
    if not named:
        log_message(f"No file given, using {source}")

    if len(named) > 1:
        return source, named[1]
    return source, default_target(source)


# --------------------------------------------------------------
def target_mark(path):
    """Read the generated marker of an existing PPTX."""
    try:
        return Presentation(path).core_properties.comments
    except Exception:
        return ""


# --------------------------------------------------------------
def check_target(target, force):
    """Refuse to overwrite a deck we did not generate."""
    if force or not os.path.isfile(target):
        return
    # The name is the primary signal: anything called
    # "-generated.pptx" is a projection and is always safe
    # to rebuild. The core-properties mark is the second
    # belt, for targets named something else.
    if target.endswith(GENERATED_SUFFIX):
        return
    if target_mark(target) == GENERATED_MARK:
        return
    log_message(
        f"ERROR: {target} was not produced by this script."
    )
    log_message(
        "It looks hand-made, so it will not be overwritten."
    )
    log_message(
        "Pass a different output name, or --force if you "
        "really mean it."
    )
    sys.exit(1)


# --------------------------------------------------------------
def build_deck(deck, bench):
    """Lay out a deck and render every page."""
    pages = L.paginate(deck.sections)
    names = all_headlines(deck)
    for page in pages:
        if page.kind == KIND_TOC and not page.title:
            page.title = deck.title
    prs = new_presentation()
    prs.core_properties.comments = GENERATED_MARK
    prs.core_properties.title = deck.title
    for page in pages:
        render_page(prs, page, names, bench, deck.epigraph)
    return prs, pages, names


# --------------------------------------------------------------
def read_deck(source):
    """Parse a deck file, failing with one clean line."""
    try:
        return parse_deck_file(source)
    except DeckError as exc:
        log_message(f"ERROR in {source}: {exc}")
        log_message(
            "Nothing was written. Fix that line and re-run."
        )
        sys.exit(1)


# --------------------------------------------------------------
def main():
    """Build the PPTX for one deck Markdown file."""
    source, target = resolve_paths(sys.argv)
    check_target(target, "--force" in sys.argv)

    log_message(f"Reading {source}")
    base = os.path.dirname(os.path.abspath(source))
    deck = read_deck(source)
    missing = resolve_images(deck, base)
    bench = load_leaderboard(base)

    prs, pages, names = build_deck(deck, bench)
    prs.save(target)

    log_message("=" * 50)
    log_message(f"Deck title: {deck.title}")
    log_message(f"Sections: {len(deck.sections)}, "
                f"news items: {len(names)}")
    log_message(f"Slides written: {len(pages)}")
    dropped, back = report_recreated(deck, source)
    log_message(f"Topics in the deleted file: {dropped}")
    if back:
        log_message(f"RECREATED deleted topics: {back}")
    if deleted_count(deck):
        log_message(f"Marked deleted in the deck: "
                    f"{deleted_count(deck)}")
    log_message(f"Missing images: {missing}")
    log_message(f"Overflowing slides: "
                f"{report_overflow(pages)}")
    report_size(target)


# --------------------------------------------------------------
def media_bytes(path):
    """Total compressed size of the pictures in a PPTX."""
    import zipfile
    with zipfile.ZipFile(path) as archive:
        return sum(
            item.compress_size
            for item in archive.infolist()
            if item.filename.startswith("ppt/media/")
        )


# --------------------------------------------------------------
def report_size(target):
    """Log the finished size, and how much is pictures."""
    total = os.path.getsize(target)
    pictures = media_bytes(target)
    share = 100 * pictures / total if total else 0
    log_message(
        f"Wrote {target} ({total / 1024:.0f} KB, "
        f"{share:.0f}% pictures)"
    )
    if total > 8 * 1024 * 1024:
        log_message(
            "This deck is large. Shrink the pictures with: "
            "python3 s2_clean_images.py --ppi 96"
        )


# --------------------------------------------------------------
if __name__ == "__main__":
    main()
